apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamlit-deployment
  template:
    metadata:
      labels:
        app: streamlit-deployment
    spec:
      containers:
      - name: streamlit-deployment
        image: royjith/pikube:latest
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8501 
      nodePort: 30007
  selector:
    app: streamlit-deployment

